idf_component_register(
    SRCS
        "app_main.c"
        "board.c"
    INCLUDE_DIRS
        "."
        "../components/Phoenix/inc"
        "../components/PCA9685"
        "../components/Servo/inc"
        "../components/PS2/inc"
        "../components/SerialProtocol/inc"
    REQUIRES
        driver
        freertos
        esp_timer
)